
// Code generated by stanc v2.27.0
#include <stan/model/model_header.hpp>
namespace PhasedIndividual_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 24> locations_array__ = 
{" (found before start of program)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 26, column 3 to column 44)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 30, column 3 to column 32)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 35, column 3 to column 30)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 36, column 3 to column 34)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 39, column 3 to column 48)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 20, column 3 to column 15)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 21, column 22 to column 29)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 21, column 3 to column 33)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 22, column 33 to column 40)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 22, column 3 to column 42)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 4, column 3 to column 17)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 6, column 6 to column 28)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 7, column 6 to column 28)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 12, column 9 to column 63)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 13, column 9 to column 63)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 14, column 9 to column 44)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 11, column 11 to line 15, column 7)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 10, column 9 to column 48)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 9, column 6 to line 15, column 7)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 5, column 27 to line 16, column 4)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 5, column 3 to line 16, column 4)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 17, column 3 to column 17)",
 " (in '/hpc/home/sh700/ase_models/PhasedIndividual.stan', line 3, column 0 to line 18, column 1)"};


template <typename T3__>
stan::promote_args_t<T3__>
likelihood(const std::vector<std::vector<int>>& count,
           const std::vector<int>& isPhased, const int& numSites,
           const T3__& p, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T3__>;
  int current_statement__ = 0; 
  static constexpr bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  try {
    local_scalar_t__ loglik;
    loglik = DUMMY_VAR__;
    
    current_statement__ = 11;
    loglik = 0;
    current_statement__ = 21;
    for (int site = 1; site <= numSites; ++site) {
      int mat;
      mat = std::numeric_limits<int>::min();
      
      current_statement__ = 12;
      mat = rvalue(count, "count", index_uni(site), index_uni(1));
      int pat;
      pat = std::numeric_limits<int>::min();
      
      current_statement__ = 13;
      pat = rvalue(count, "count", index_uni(site), index_uni(2));
      current_statement__ = 19;
      if (rvalue(isPhased, "isPhased", index_uni(site))) {
        current_statement__ = 18;
        loglik = (loglik + binomial_lpmf<false>(mat, (mat + pat), p));
      } else {
        local_scalar_t__ phase1;
        phase1 = DUMMY_VAR__;
        
        current_statement__ = 14;
        phase1 = (stan::math::log(0.5) +
                   binomial_lpmf<false>(mat, (mat + pat), p));
        local_scalar_t__ phase2;
        phase2 = DUMMY_VAR__;
        
        current_statement__ = 15;
        phase2 = (stan::math::log(0.5) +
                   binomial_lpmf<false>(pat, (mat + pat), p));
        current_statement__ = 16;
        loglik = (loglik + log_sum_exp(phase1, phase2));
      }
    }
    current_statement__ = 22;
    return loglik;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}

struct likelihood_functor__ {
template <typename T3__>
stan::promote_args_t<T3__>
operator()(const std::vector<std::vector<int>>& count,
           const std::vector<int>& isPhased, const int& numSites,
           const T3__& p, std::ostream* pstream__)  const 
{
return likelihood(count, isPhased, numSites, p, pstream__);
}
};

class PhasedIndividual_model final : public model_base_crtp<PhasedIndividual_model> {

 private:
  int N_SITES;
  std::vector<std::vector<int>> count;
  std::vector<int> isPhased; 
  
 
 public:
  ~PhasedIndividual_model() { }
  
  inline std::string model_name() const final { return "PhasedIndividual_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.27.0", "stancflags = "};
  }
  
  
  PhasedIndividual_model(stan::io::var_context& context__,
                         unsigned int random_seed__ = 0,
                         std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "PhasedIndividual_model_namespace::PhasedIndividual_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 6;
      context__.validate_dims("data initialization","N_SITES","int",
           std::vector<size_t>{});
      N_SITES = std::numeric_limits<int>::min();
      
      current_statement__ = 6;
      N_SITES = context__.vals_i("N_SITES")[(1 - 1)];
      current_statement__ = 7;
      validate_non_negative_index("count", "N_SITES", N_SITES);
      current_statement__ = 8;
      context__.validate_dims("data initialization","count","int",
           std::vector<size_t>{static_cast<size_t>(N_SITES),
            static_cast<size_t>(2)});
      count = std::vector<std::vector<int>>(N_SITES, std::vector<int>(2, std::numeric_limits<int>::min()));
      
      
      {
        std::vector<int> count_flat__;
        current_statement__ = 8;
        count_flat__ = context__.vals_i("count");
        current_statement__ = 8;
        pos__ = 1;
        current_statement__ = 8;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 8;
          for (int sym2__ = 1; sym2__ <= N_SITES; ++sym2__) {
            current_statement__ = 8;
            assign(count, count_flat__[(pos__ - 1)],
              "assigning variable count", index_uni(sym2__),
                                            index_uni(sym1__));
            current_statement__ = 8;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 8;
      for (int sym1__ = 1; sym1__ <= N_SITES; ++sym1__) {
        current_statement__ = 8;
        for (int sym2__ = 1; sym2__ <= 2; ++sym2__) {
          current_statement__ = 8;
          check_greater_or_equal(function__, "count[sym1__, sym2__]",
                                 count[(sym1__ - 1)][(sym2__ - 1)], 0);
        }
      }
      current_statement__ = 9;
      validate_non_negative_index("isPhased", "N_SITES", N_SITES);
      current_statement__ = 10;
      context__.validate_dims("data initialization","isPhased","int",
           std::vector<size_t>{static_cast<size_t>(N_SITES)});
      isPhased = std::vector<int>(N_SITES, std::numeric_limits<int>::min());
      
      current_statement__ = 10;
      isPhased = context__.vals_i("isPhased");
      current_statement__ = 10;
      for (int sym1__ = 1; sym1__ <= N_SITES; ++sym1__) {
        current_statement__ = 10;
        check_greater_or_equal(function__, "isPhased[sym1__]",
                               isPhased[(sym1__ - 1)], 0);
      }
      current_statement__ = 10;
      for (int sym1__ = 1; sym1__ <= N_SITES; ++sym1__) {
        current_statement__ = 10;
        check_less_or_equal(function__, "isPhased[sym1__]",
                            isPhased[(sym1__ - 1)], 1);
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "PhasedIndividual_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ theta;
      theta = DUMMY_VAR__;
      
      current_statement__ = 1;
      theta = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(
                0.000001, 1000000, lp__);
      local_scalar_t__ p;
      p = DUMMY_VAR__;
      
      current_statement__ = 2;
      p = (theta / (1 + theta));
      {
        current_statement__ = 3;
        lp_accum__.add(normal_lpdf<propto__>(stan::math::log2(theta), 0, 1));
        current_statement__ = 4;
        lp_accum__.add(-stan::math::log((theta * stan::math::log(2))));
        current_statement__ = 5;
        lp_accum__.add(likelihood(count, isPhased, N_SITES, p, pstream__));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "PhasedIndividual_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double theta;
      theta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      theta = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(
                0.000001, 1000000, lp__);
      double p;
      p = std::numeric_limits<double>::quiet_NaN();
      
      vars__.emplace_back(theta);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 2;
      p = (theta / (1 + theta));
      if (emit_transformed_parameters__) {
        vars__.emplace_back(p);
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    int current_statement__ = 0; 
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double theta;
      theta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      theta = context__.vals_r("theta")[(1 - 1)];
      double theta_free__;
      theta_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      theta_free__ = stan::math::lub_free(theta, 0.000001, 1000000);
      vars__.emplace_back(theta_free__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"theta", "p"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "theta");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "p");
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "theta");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "p");
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"theta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"p\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"theta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"p\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec;
      vars_vec.reserve(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars,
       emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec;
      params_r_vec.reserve(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }

};
}
using stan_model = PhasedIndividual_model_namespace::PhasedIndividual_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return PhasedIndividual_model_namespace::profiles__;
}

#endif


